plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.6'
}

group = 'dev.soulcaskets'
version = '1.0.0'

repositories {
    maven { url = uri('https://repo.papermc.io/repository/maven-public/') }
}

dependencies {
    compileOnly('io.papermc.paper:paper-api:26.1.2.build.+')
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(25))
}

tasks {
    shadowJar {
        archiveClassifier.set('')
        archiveFileName.set("SoulCaskets-${version}.jar")
    }

    build {
        dependsOn shadowJar
    }

    processResources {
        filesMatching('plugin.yml') {
            expand(version: version)
        }
    }
}
